version: "3.7"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./db/mysql:/var/lib/mysql"
      - "./db/data:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: rootdb
      MYSQL_USER: cn_user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306